namespace MessageFlow.Core.Localization;

/// <summary>
/// English UI strings. This is the reference table: every other language is validated
/// against these keys, and any key missing elsewhere falls back to the English text.
/// </summary>
public static class UiStringsEnglish
{
    public static IReadOnlyDictionary<string, string> Values { get; } = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        // ---- Common ----
        ["Common_Close"] = "Close",
        ["Common_Cancel"] = "Cancel",
        ["Common_Browse"] = "Browse",
        ["Common_Save"] = "Save",
        ["Common_Search"] = "Search",
        ["Common_Project"] = "Project",
        ["Common_Copy"] = "Copy",
        ["Common_Admin"] = "Admin",
        ["Common_Clear"] = "Clear",
        ["Common_Preview"] = "Preview",
        ["Common_Import"] = "Import",
        ["Common_Title"] = "Title",
        ["Common_Author"] = "Author",
        ["Common_Description"] = "Description",
        ["Common_Language"] = "Language",
        ["Common_Status"] = "Status",
        ["Common_Folder"] = "Folder",
        ["Common_Ready"] = "Ready",
        ["Common_Dash"] = "-",

        // ---- Language selector ----
        ["Lang_SelectorTooltip"] = "Change the application language",
        ["Lang_Changed"] = "Application language set to {0}.",
        ["Lang_ChangedToEnglish"] = "Application language set to English.",
        ["Lang_ChangedToFrench"] = "Application language set to French.",

        // ---- Top toolbar ----
        ["Toolbar_SearchSermonsTooltip"] = "Search sermons by title, code, phrase, or paragraph number",
        ["Toolbar_FontSizeTooltip"] = "Projection font size",
        ["Toolbar_DecreaseTextTooltip"] = "Decrease text size",
        ["Toolbar_FitTextTooltip"] = "Fit text to screen",
        ["Toolbar_IncreaseTextTooltip"] = "Increase text size",
        ["Toolbar_Fit"] = "Fit",

        // ---- Navigation / library ----
        ["Nav_Library"] = "Library",
        ["Nav_Sermons"] = "Sermons",
        ["Nav_Bible"] = "Bible",
        ["Nav_Songs"] = "Songs",
        ["Nav_Favorites"] = "Favorites",
        ["Nav_History"] = "History",

        // ---- Centre / preview panels ----
        ["Panel_BiblePreview"] = "Bible Preview",
        ["Panel_SongSections"] = "Song Sections",
        ["Panel_ReadingSermon"] = "Reading Sermon",
        ["Panel_LiveProjection"] = "Live / Projection",
        ["Panel_SearchResults"] = "Search Results",
        ["Panel_SermonsBreadcrumb"] = "Sermons > {0}",

        // ---- Sermons ----
        ["Sermon_SearchHint"] = "Search sermons by title, code, phrase, or paragraph number.",
        ["Sermon_SearchHintShort"] = "Search by sermon title, code, phrase, or paragraph number.",
        ["Sermon_Open"] = "Open Sermon",
        ["Sermon_OpenTooltip"] = "Open every paragraph in this Sermon for focused reading",
        ["Sermon_OpenSelectedTooltip"] = "Open every paragraph in the selected Sermon for focused reading",
        ["Sermon_ReadyToSearch"] = "Ready to search sermons.",
        ["Sermon_ReadyToSearchHeader"] = "Ready to search sermons",
        ["Sermon_Back"] = "Back",
        ["Sermon_BackTooltip"] = "Return to the previous global Sermon results",
        ["Sermon_FindInTooltip"] = "Find in selected sermon",
        ["Sermon_PreviousMatch"] = "Previous Match",
        ["Sermon_NextMatch"] = "Next Match",
        ["Sermon_PreviousPage"] = "Previous Page",
        ["Sermon_NextPage"] = "Next Page",
        ["Sermon_PreviousParagraph"] = "Previous Paragraph",
        ["Sermon_NextParagraph"] = "Next Paragraph",
        ["Sermon_ParagraphLabel"] = "Paragraph {0}",
        ["Sermon_NoFrenchContent"] = "No French sermons are available yet.",
        ["Sermon_NoFrenchContentDetail"] = "French sermons have not been added to this library. English sermons stay in the English interface and are never shown as French content.",
        ["Sermon_NoContentForLanguage"] = "No sermons are available in {0} yet.",
        ["Sermon_NoContentForLanguageDetail"] = "Sermons in {0} have not been added to this library. Content in other languages stays in its own interface and is never shown here.",

        // ---- Bible ----
        ["Bible_SearchHint"] = "Search by book, chapter, verse, or keyword.",
        ["Bible_SearchTooltip"] = "Search Bible references or keywords",
        ["Bible_NotAvailable"] = "Bible is not available. Open Admin Tools if setup is needed.",
        ["Bible_ReadyToSearch"] = "Ready to search the Bible.",
        ["Bible_ReadyToSearchHeader"] = "Ready to search the Bible",
        ["Bible_ReferenceExamples"] = "Examples: John 3:16, Romans 8:28, Psalm 23.",
        ["Bible_PreviousVerse"] = "Previous Verse",
        ["Bible_NextVerse"] = "Next Verse",
        ["Bible_AddFavorite"] = "Add Bible Favorite",
        ["Bible_RemoveFavorite"] = "Remove Bible Favorite",
        ["Bible_Book"] = "Book",
        ["Bible_Chapter"] = "Chapter",
        ["Bible_SelectBookHint"] = "Select this book to choose a chapter.",
        ["Bible_SelectChapterHint"] = "Select this chapter to choose a verse.",
        ["Bible_ChapterMeta"] = "Chapter | {0}",
        ["Bible_NoTranslationForLanguage"] = "No Bible translation is available for this language yet.",

        // ---- Songs ----
        ["Song_SearchHint"] = "Search songs by title or lyrics.",
        ["Song_SearchTooltip"] = "Search songs by title or lyrics",
        ["Song_SearchHintShort"] = "Search by title or lyric phrase.",
        ["Song_ReadyToSearch"] = "Ready to search songs.",
        ["Song_ReadyToSearchHeader"] = "Ready to search songs",
        ["Song_PreviousSection"] = "Previous Section",
        ["Song_NextSection"] = "Next Section",
        ["Song_Source"] = "Song source",
        ["Song_NoFrenchContent"] = "No French songs are available yet.",
        ["Song_NoFrenchContentDetail"] = "French songs have not been added to this library. English songs stay in the English interface and are never shown as French content.",
        ["Song_NoContentForLanguage"] = "No songs are available in {0} yet.",
        ["Song_NoContentForLanguageDetail"] = "Songs in {0} have not been added to this library. Content in other languages stays in its own interface and is never shown here.",

        // ---- Favorites ----
        ["Fav_None"] = "No favorites yet.",
        ["Fav_NoneDetail"] = "Save frequently used sermon paragraphs or Bible verses for quick access.",
        ["Fav_SermonSection"] = "Sermon Favorites",
        ["Fav_BibleSection"] = "Bible Favorites",
        ["Fav_NoSermonFavorites"] = "No sermon favorites yet.",
        ["Fav_NoBibleFavorites"] = "No Bible favorites yet.",
        ["Fav_Remove"] = "Remove Favorite",
        ["Fav_Add"] = "Add Favorite",
        ["Fav_SavedAt"] = "Saved {0}",

        // ---- History ----
        ["History_Recent"] = "Recent projections",
        ["History_Clear"] = "Clear History",
        ["History_None"] = "No projection history yet.",

        // ---- Count nouns (singular / plural) ----
        ["Count_BibleResult_One"] = "Bible result",
        ["Count_BibleResult_Many"] = "Bible results",
        ["Count_Song_One"] = "song",
        ["Count_Song_Many"] = "songs",
        ["Count_Sermon_One"] = "sermon",
        ["Count_Sermon_Many"] = "sermons",
        ["Count_Paragraph_One"] = "paragraph",
        ["Count_Paragraph_Many"] = "paragraphs",
        ["Count_Chapter_One"] = "chapter",
        ["Count_Chapter_Many"] = "chapters",
        ["Count_Verse_One"] = "verse",
        ["Count_Verse_Many"] = "verses",
        ["Count_NoResults"] = "No results found",

        // ---- Admin Tools window ----
        ["Admin_Title"] = "Admin Tools",
        ["Admin_Subtitle"] = "Setup and maintenance tools for an administrator. These controls are not needed during a normal service.",
        ["Admin_Section1"] = "1. Displays",
        ["Admin_Section1Detail"] = "Choose and verify the church projection display.",
        ["Admin_TestProjection"] = "Test Projection Display",
        ["Admin_TestProjectionTooltip"] = "Show a test pattern on the configured display",
        ["Admin_OpenProjectionPreview"] = "Open Projection Preview",
        ["Admin_OpenProjectionPreviewTooltip"] = "Open a resizable local preview window",
        ["Admin_RefreshDisplays"] = "Refresh Displays",
        ["Admin_RefreshDisplaysTooltip"] = "Detect connected monitors again",
        ["Admin_Section2"] = "2. Library Import",
        ["Admin_Section2Detail"] = "Scan and review local content before it enters the searchable library.",
        ["Admin_OpenLibraryImport"] = "Open Library Import",
        ["Admin_OpenLibraryImportTooltip"] = "Import local Brother Frank PDFs or additional Song files into managed storage",
        ["Admin_ManageSources"] = "Manage Existing Sources",
        ["Admin_ManageSourcesTooltip"] = "Review configured Sermon content sources",
        ["Admin_AddSermonSource"] = "Add Sermon Source",
        ["Admin_AddSermonSourceTooltip"] = "Configure a legacy local PDF folder source",
        ["Admin_ImportSelectedSource"] = "Import Selected Source",
        ["Admin_ImportSelectedSourceTooltip"] = "Scan and import the selected configured source",
        ["Admin_ImportBible"] = "Import Bible",
        ["Admin_ImportBibleTooltip"] = "Import a reviewed Bible CSV file",
        ["Admin_Section3"] = "3. Search Maintenance",
        ["Admin_Section3Detail"] = "Repair metadata or rebuild the local Sermon search index without changing religious text.",
        ["Admin_RepairMetadata"] = "Repair Selected Source Metadata",
        ["Admin_RepairMetadataTooltip"] = "Re-read titles and codes from source filenames; paragraph text is unchanged",
        ["Admin_RebuildIndex"] = "Rebuild Sermon Search Index",
        ["Admin_RebuildIndexTooltip"] = "Rebuild the SQLite Sermon index from stored paragraph text",
        ["Admin_Section4"] = "4. Database / Backup",
        ["Admin_Section4Detail"] = "Protect the library before large imports or maintenance.",
        ["Admin_BackupDatabase"] = "Backup Database",
        ["Admin_RestoreDatabase"] = "Restore Database",
        ["Admin_OpenBackupFolder"] = "Open Backup Folder",
        ["Admin_VerifyProductionData"] = "Verify Production Data",
        ["Admin_VerifyProductionDataTooltip"] = "Run protected Bible, Song, and Sermon count checks",
        ["Admin_Section5"] = "5. About / System Information",
        ["Admin_AdvancedCleanup"] = "Advanced cleanup (administrator only)",
        ["Admin_AdvancedCleanupDetail"] = "These actions always show a review or confirmation before changing data.",
        ["Admin_CleanupTestData"] = "Cleanup Test Data",
        ["Admin_CleanupTestDataTooltip"] = "Review and remove records identified as test data",
        ["Admin_CleanupBrotherFrank"] = "Cleanup Brother Frank Circular Letters",
        ["Admin_CleanupBrotherFrankTooltip"] = "Review and remove imported circular-letter records only",

        // ---- Import Bible window ----
        ["ImportBible_Title"] = "Import Bible",
        ["ImportBible_Subtitle"] = "Select a reviewed Bible CSV file with the columns book, chapter, verse, text.",
        ["ImportBible_SuggestedFile"] = "Suggested folder: Documents\\Bible",
        ["ImportBible_TranslationName"] = "Translation Name",
        ["ImportBible_Abbreviation"] = "Abbreviation",
        ["ImportBible_Language"] = "Language",
        ["ImportBible_CsvFile"] = "CSV File",
        ["ImportBible_ChooseFileHint"] = "Choose a CSV file and click Preview.",
        ["ImportBible_Translation"] = "Translation",
        ["ImportBible_VersesFound"] = "Verses Found",
        ["ImportBible_InvalidRows"] = "Invalid Rows",
        ["ImportBible_SampleVerses"] = "First 10 sample verses",
        ["ImportBible_InvalidRowsList"] = "Invalid rows",
        ["ImportBible_NoInvalidRows"] = "No invalid rows found.",
        ["ImportBible_Footer"] = "Preview checks the file only. Start Import writes the previewed verses to the database.",
        ["ImportBible_StartImport"] = "Start Import",
        ["ImportBible_PreviewReady"] = "Preview ready.",
        ["ImportBible_PreviewFailed"] = "Preview failed.",
        ["ImportBible_NoValidVerses"] = "No valid verses found.",
        ["ImportBible_FixInvalidRows"] = "Fix invalid rows before importing.",
        ["ImportBible_ClickPreview"] = "Click Preview to inspect the CSV.",
        ["ImportBible_NameRequired"] = "Translation name is required.",
        ["ImportBible_AbbreviationRequired"] = "Abbreviation is required.",
        ["ImportBible_LanguageRequired"] = "Language is required.",
        ["ImportBible_SelectExistingFile"] = "Select an existing local Bible CSV file.",
        ["ImportBible_NoCleanPreview"] = "No clean Bible preview is ready to import.",
        ["ImportBible_SelectCsvDialog"] = "Select Bible CSV",
        ["ImportBible_PreviewErrorTitle"] = "Import Bible Preview",
        ["ImportBible_AlreadyExists"] = "{0} already exists. Replace existing verses?",
        ["ImportBible_ImportedMessage"] = "Imported {0} verses for {1} ({2}).",

        // ---- Import preview window ----
        ["ImportPreview_Title"] = "Import Preview",
        ["ImportPreview_Source"] = "Source",
        ["ImportPreview_Type"] = "Type",
        ["ImportPreview_EstimatedAuthor"] = "Estimated author",
        ["ImportPreview_PdfFilesFound"] = "PDF files found",
        ["ImportPreview_ReadyToImport"] = "Ready to import",
        ["ImportPreview_AlreadyImported"] = "Already imported",
        ["ImportPreview_InvalidOrMissing"] = "Invalid or missing",
        ["ImportPreview_QualityHeading"] = "Brother Frank paragraph quality preview",
        ["ImportPreview_TotalParagraphs"] = "Total extracted paragraphs",
        ["ImportPreview_AcceptedParagraphs"] = "Accepted paragraphs",
        ["ImportPreview_RejectedPageNumbers"] = "Rejected page numbers",
        ["ImportPreview_RejectedCorrupted"] = "Rejected corrupted text",
        ["ImportPreview_RejectedHeaders"] = "Rejected headers/footers",
        ["ImportPreview_RejectedTooShort"] = "Rejected too short",
        ["ImportPreview_SampleMetadata"] = "Sample parsed metadata",
        ["ImportPreview_CodeYear"] = "Code / Year",
        ["ImportPreview_TypeStatus"] = "Type / Status",
        ["ImportPreview_InvalidFiles"] = "Invalid or missing files",
        ["ImportPreview_Footer"] = "Cancel stops here. Start Import writes only new local PDFs to the database.",

        // ---- Library import window ----
        ["LibraryImport_Title"] = "Library Import",
        ["LibraryImport_Subtitle"] = "Import files already downloaded to this computer. Accepted files are copied into MessageFlow-managed storage. No Internet access, AI completion, or OCR is used.",
        ["LibraryImport_BrotherFrank"] = "Brother Frank Publications",
        ["LibraryImport_AdditionalSongs"] = "Additional Songs",
        ["LibraryImport_BrowseFiles"] = "Browse Files",
        ["LibraryImport_BrowseFilesTooltip"] = "Choose one or more local files",
        ["LibraryImport_BrowseFolder"] = "Browse Folder",
        ["LibraryImport_BrowseFolderTooltip"] = "Choose a local folder to scan",
        ["LibraryImport_ColumnImport"] = "Import",
        ["LibraryImport_ColumnFile"] = "File",
        ["LibraryImport_ColumnTitle"] = "Title (editable)",
        ["LibraryImport_ColumnItems"] = "Items",
        ["LibraryImport_ColumnStatus"] = "Scan / Import status",
        ["LibraryImport_Hint"] = "Choose files or a folder, then review the scan results.",
        ["LibraryImport_ImportSelected"] = "Import Selected",
        ["LibraryImport_ImportSelectedTooltip"] = "Copy and transactionally import checked files",

        // ---- Manage sources window ----
        ["ManageSources_Title"] = "Manage Sources",
        ["ManageSources_Subtitle"] = "Review local folders and run source imports from here.",
        ["ManageSources_ShowTestSources"] = "Show test sources",
        ["ManageSources_Sources"] = "Sources",
        ["ManageSources_Documents"] = "Documents",
        ["ManageSources_Paragraphs"] = "Paragraphs",
        ["ManageSources_RepairMetadata"] = "Repair Metadata",
        ["ManageSources_AdvancedDetails"] = "Advanced Details",
        ["ManageSources_LocalPdfs"] = "Local PDFs",
        ["ManageSources_TestSource"] = "Test source",
        ["ManageSources_Suspicious"] = "Suspicious",
        ["ManageSources_AddSource"] = "Add Source",

        // ---- Add content source window ----
        ["AddSource_Title"] = "Add New Source",
        ["AddSource_Subtitle"] = "Register a local content folder for future imports.",
        ["AddSource_DisplayName"] = "Display Name",
        ["AddSource_SourceType"] = "Source Type",
        ["AddSource_LocalFolderPath"] = "Local Folder Path",
        ["AddSource_Save"] = "Save Source",

        // ---- Production verification window ----
        ["Verify_Title"] = "Production Data Check",
        ["Verify_Subtitle"] = "A simple readiness report for church media use.",

        // ---- Test data cleanup window ----
        ["Cleanup_Title"] = "Cleanup Test Data",
        ["Cleanup_Documents"] = "Documents: ",
        ["Cleanup_Paragraphs"] = "  Paragraphs: ",
        ["Cleanup_Favorites"] = "  Favorites: ",
        ["Cleanup_History"] = "  History: ",
        ["Cleanup_TypePhrase"] = "Type this confirmation phrase to continue:",
        ["Cleanup_Phrase"] = "I understand this removes test source data only.",
        ["Cleanup_BackupNotice"] = "A database backup will be created before anything is deleted.",

        // ---- Projection window ----
        ["Projection_Title"] = "MessageFlow Projection",

        // ---- Status messages ----
        ["Status_Ready"] = "Ready",
        ["Status_ProjectionDisplaySet"] = "Projection display set to {0}.",
        ["Status_Selected"] = "Selected {0}.",
        ["Status_SelectedParagraph"] = "Selected Paragraph {0}.",
        ["Status_Projecting"] = "Projecting {0}.",
        ["Status_ProjectingParagraph"] = "Projecting Paragraph {0}.",
        ["Status_ProjectingSongSection"] = "Projecting {0} - {1}.",
        ["Status_MetadataRefreshed"] = "Brother Frank publication metadata refreshed.",
        ["Status_MetadataRefreshFailed"] = "Brother Frank publication metadata could not be refreshed. Admin repair remains available.",
        ["Status_LibrarySearchable"] = "Imported library content is searchable now.",
        ["Status_HistoryKept"] = "History was kept.",
        ["Status_HistoryCleared"] = "History cleared.",
        ["Status_HistoryClearFailed"] = "History could not be cleared: {0}",
        ["Status_VerifyingProductionData"] = "Verifying production data...",
        ["Status_ProductionVerificationFailed"] = "Production verification failed: {0}",
        ["Status_IndexRebuildCanceled"] = "Sermon search index rebuild canceled.",
        ["Status_RebuildingIndex"] = "Rebuilding Sermon search index...",
        ["Status_IndexRebuilt"] = "Sermon search index rebuilt.",
        ["Status_IndexRebuildFailed"] = "Sermon search index rebuild failed: {0}",
        ["Status_CheckingTestData"] = "Checking for test data...",
        ["Status_NoTestData"] = "No test data was found.",
        ["Status_TestCleanupCanceled"] = "Test data cleanup canceled.",
        ["Status_TestCleanupCompleted"] = "Test data cleanup completed.",
        ["Status_TestCleanupFailed"] = "Test data cleanup failed: {0}",
        ["Status_CheckingBrotherFrank"] = "Checking Brother Frank Circular Letter imports...",
        ["Status_BrotherFrankPreviewFailed"] = "Brother Frank cleanup preview failed: {0}",
        ["Status_NoBrotherFrankImports"] = "No Brother Frank Circular Letter imports were found.",
        ["Status_BrotherFrankCanceled"] = "Brother Frank cleanup canceled.",
        ["Status_RemovingBrotherFrank"] = "Removing Brother Frank Circular Letter imports...",
        ["Status_BrotherFrankFailed"] = "Brother Frank cleanup failed: {0}",
        ["Status_BackingUp"] = "Backing up database...",
        ["Status_BackupCompleted"] = "Backup completed successfully:{0}{1}",
        ["Status_BackupFailed"] = "Backup failed: {0}",
        ["Status_Restoring"] = "Restoring database...",
        ["Status_RestoreCompleted"] = "Restore completed successfully.",
        ["Status_RestoreFailed"] = "Restore failed: {0}",
        ["Status_NoBackupYet"] = "No backup has been created yet.",
        ["Status_BackupFolderMissing"] = "Backup folder could not be found.",
        ["Status_OpenBackupFolderFailed"] = "Open backup folder failed: {0}",
        ["Status_SavingSource"] = "Saving content source...",
        ["Status_SourceExists"] = "A source named {0} already exists.",
        ["Status_SourceAdded"] = "Source added: {0}.",
        ["Status_SourceSaveFailed"] = "Source save failed: {0}",
        ["Status_BibleImportCanceled"] = "Bible import canceled. No database changes were made.",
        ["Status_NoBibleVerses"] = "No Bible verses are ready to import.",
        ["Status_PreparingBibleImport"] = "Preparing {0} Bible import...",
        ["Status_BibleImportKeptExisting"] = "Bible import canceled. Existing verses were kept.",
        ["Status_BibleImported"] = "Imported {0}: {1} verses.",
        ["Status_BibleImportFailed"] = "Bible import failed: {0}",
        ["Status_SelectSourceFirst"] = "Select a source before importing.",
        ["Status_ImportComingSoon"] = "Import for this source type is coming soon.",
        ["Status_SourceFolderMissing"] = "Source folder does not exist.",
        ["Status_ScanningSource"] = "Scanning {0} for import preview...",
        ["Status_ImportPreviewFailed"] = "Import preview failed: {0}",
        ["Status_ImportCanceled"] = "Import canceled. No database changes were made.",
        ["Status_NoNewPdfs"] = "No new PDF files are ready to import.",
        ["Status_StartingImport"] = "Starting import for {0}...",
        ["Status_SourceImportFailed"] = "Source import failed: {0}",
        ["Status_SelectSourceRepair"] = "Select a source before repairing metadata.",
        ["Status_BranhamProtected"] = "Brother Branham metadata is protected and was not changed.",
        ["Status_RepairLimited"] = "This repair is currently limited to Ewald Frank publication sources.",
        ["Status_CheckingRepairPreview"] = "Checking repair preview for {0}...",
        ["Status_RepairPreviewFailed"] = "Source metadata repair preview failed: {0}",
        ["Status_NoDocumentsForSource"] = "No documents were found for {0}.",
        ["Status_RepairCanceled"] = "Source metadata repair canceled.",
        ["Status_RepairingMetadata"] = "Repairing metadata for {0}...",
        ["Status_RepairFailed"] = "Source metadata repair failed: {0}",
        ["Status_UseSearchInsideSermon"] = "Use Search Inside This Sermon, or go Back to Search Results.",
        ["Status_SearchingBible"] = "Searching Bible...",
        ["Status_BibleSearchFailed"] = "Bible search failed: {0}",
        ["Status_ChaptersFound"] = "{0} found for {1}.",
        ["Status_NoMatchingVerse"] = "No matching Bible verse found.",
        ["Status_BibleQuickProjectFailed"] = "Bible quick project failed: {0}",
        ["Status_SongSearchFailed"] = "Song search failed: {0}",
        ["Status_SongSectionsFailed"] = "Could not load song sections: {0}",
        ["Status_Searching"] = "Searching...",
        ["Status_NoMatchingParagraph"] = "No matching paragraph found.",
        ["Status_SearchFailed"] = "Search failed: {0}",
        ["Status_SelectSermonThenOpen"] = "Select a Sermon, then choose Open Sermon.",
        ["Status_CouldNotOpenSermon"] = "Could not open Sermon: {0}",
        ["Status_CouldNotMoveBible"] = "Could not move Bible selection: {0}",
        ["Status_SelectVerseBeforeCopy"] = "Please select a Bible verse before copying.",
        ["Status_BibleVerseCopied"] = "Bible verse copied.",
        ["Status_SelectSectionBeforeCopy"] = "Please select a song section before copying.",
        ["Status_SongSectionCopied"] = "Song section copied.",
        ["Status_ParagraphCopied"] = "Paragraph copied.",
        ["Status_SelectParagraphBeforeProject"] = "Please select a paragraph before projecting.",
        ["Status_SelectSavedParagraphBeforeProject"] = "Please select a saved paragraph before projecting.",
        ["Status_SelectBibleFavoriteBeforeProject"] = "Please select a Bible favorite before projecting.",
        ["Status_SelectBibleFavoriteBeforeCopy"] = "Please select a Bible favorite before copying.",
        ["Status_Copied"] = "Copied {0}.",
        ["Status_SelectFavoriteToRemove"] = "Please select a favorite to remove.",
        ["Status_FavoriteRemoved"] = "Favorite removed.",
        ["Status_FavoriteRemoveFailed"] = "Favorite could not be removed: {0}",
        ["Status_SelectBibleFavoriteToRemove"] = "Please select a Bible favorite to remove.",
        ["Status_RemovedFromFavorites"] = "Removed {0} from favorites.",
        ["Status_BibleFavoriteRemoveFailed"] = "Bible favorite could not be removed: {0}",
        ["Status_SelectVerseBeforeProject"] = "Please select a Bible verse before projecting.",
        ["Status_SelectSectionBeforeProject"] = "Please select a song section before projecting.",
        ["Status_SongFavoritesNotEnabled"] = "Song favorites are not enabled yet.",
        ["Status_ParagraphAddedToFavorites"] = "Paragraph added to favorites.",
        ["Status_ParagraphRemovedFromFavorites"] = "Paragraph removed from favorites.",
        ["Status_FavoriteUpdateFailed"] = "Favorite update failed: {0}",
        ["Status_AddedToFavorites"] = "Added {0} to favorites.",
        ["Status_BibleFavoriteUpdateFailed"] = "Bible favorite update failed: {0}",
        ["Status_SavedParagraphMissing"] = "Saved paragraph could not be found.",
        ["Status_CouldNotSelectSavedParagraph"] = "Could not select saved paragraph: {0}",
        ["Status_NoContentSources"] = "No content sources configured yet.",
        ["Status_ProjectionTextDecreased"] = "Projection text decreased by 2 DIPs.",
        ["Status_ProjectionTextRestored"] = "Projection text restored to the largest safe fit.",
        ["Status_SavedToHistory"] = "Saved to projection history.",
        ["Status_HistoryUpdateFailed"] = "Projection history update failed: {0}",

        // ---- Bible / translation info ----
        ["Info_CurrentTranslation"] = "Current Bible: {0} ({1})",
        ["Info_NoTranslation"] = "No Bible translation is loaded.",
        ["Info_NoTranslationImported"] = "No Bible translation imported yet.",
        ["Info_VersionNone"] = "Version: none",
        ["Info_Version"] = "Version: {0}",
        ["Info_NoVersesImported"] = "No Bible verses imported.",
        ["Info_VerseCount"] = "{0} verses available.",

        ["Filter_AllAuthors"] = "All Authors",
        ["Filter_AllSources"] = "All Sources",
        ["Filter_AllYears"] = "All Years",
        ["Font_Small"] = "Small",
        ["Font_Medium"] = "Medium",
        ["Font_Large"] = "Large",
        ["Font_ExtraLarge"] = "Extra Large",
        ["Panel_CircularLetterResults"] = "Circular Letter Results",
        ["Panel_SermonResults"] = "Sermon Results",
        ["Count_BibleBook_One"] = "Bible book",
        ["Count_BibleBook_Many"] = "Bible books",
        ["Count_Document_One"] = "document",
        ["Count_Document_Many"] = "documents",
        ["Status_LoadingSongs"] = "Loading songs...",
        ["Status_SearchingSongs"] = "Searching songs...",
        ["Status_NoSongsFound"] = "No songs found.",
        ["Status_NoBibleMatches"] = "No Bible matches found.",
        ["Status_VerseNotFound"] = "{0} was not found.",
        ["Status_VersesFoundIn"] = "{0} found in {1}.",
        ["Status_SelectedInChapterContext"] = "Selected {0} in chapter context.",
        ["Status_BooksFound"] = "{0} found.",
        ["Status_StartupFailed"] = "Startup initialization failed. See logs\\app-startup.log.",
        ["Status_FindInSermon"] = "Find in selected Sermon.",
        ["Status_ProjectionOpen"] = "Projection: Open on {0}",
        ["Status_ProjectionClosed"] = "Projection: Closed",
        ["Status_NoExactPhrase"] = "No exact phrase found",
        ["Status_ExactPhrase"] = "Exact phrase",
        ["Status_AllWords"] = "All words",
        ["Status_Match"] = "Match",
        ["Status_BrowseFound"] = "{0} found in {1} ms.",
        ["Status_SearchFound"] = "{0} found in {1} ({2}) in {3} ms.",
        ["Status_SearchNoMatch"] = "{0} in {1} ms.",
        ["Fav_KindFavorite"] = "Favorite",
        ["Fav_KindHistory"] = "History",
        ["Meta_Paragraph"] = "Paragraph {0}",
        ["Sermon_FindInSelected"] = "Find in selected Sermon.",
        ["Display_Auto"] = "Auto - prefer secondary projection display",
        ["Display_Primary"] = "Primary / Operator",
        ["Display_Secondary"] = "Secondary / Projection",
        ["Display_Selector"] = "Display {0} - {1} - {2}x{3}",
        ["Display_StatusPrimary"] = "Display {0} Primary / Operator",
        ["Display_StatusSecondary"] = "Display {0} Secondary / Projection",
        ["Confirm_ClearHistory"] = "Clear all projection history? This will not delete sermons, Bible verses, favorites, or sources.",
        ["Confirm_ClearHistoryTitle"] = "Clear History",
        ["Confirm_RebuildIndex"] = "Rebuild the Sermon search index? This does not modify Sermon text, PDF imports, Bible verses, songs, favorites, or projection history.",
        ["Confirm_RebuildIndexTitle"] = "Rebuild Sermon Search Index",
        ["Confirm_RestoreDatabase"] = "Restoring will replace the current database. Continue?",
        ["Confirm_RestoreDatabaseTitle"] = "Restore MessageFlow Database",
        ["Confirm_ImportBibleReplace"] = "{0} already exists. Replace existing verses?",
        ["Msg_StartupFailed"] = "MessageFlow opened, but startup initialization failed.{0}{0}{1}{0}{0}Details were written to logs\\app-startup.log.",
        ["Msg_StartupFailedTitle"] = "MessageFlow Startup Error"
    };
}
