namespace MessageFlow.Core.Localization;

/// <summary>
/// French UI strings. Keys mirror <see cref="UiStringsEnglish"/>; the localization
/// coverage check reports any key that is present in English but missing here.
/// </summary>
public static class UiStringsFrench
{
    public static IReadOnlyDictionary<string, string> Values { get; } = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        // ---- Commun ----
        ["Common_Close"] = "Fermer",
        ["Common_Cancel"] = "Annuler",
        ["Common_Browse"] = "Parcourir",
        ["Common_Save"] = "Enregistrer",
        ["Common_Search"] = "Rechercher",
        ["Common_Project"] = "Projeter",
        ["Common_Copy"] = "Copier",
        ["Common_Admin"] = "Administration",
        ["Common_Clear"] = "Effacer",
        ["Common_Preview"] = "Aperçu",
        ["Common_Import"] = "Importer",
        ["Common_Title"] = "Titre",
        ["Common_Author"] = "Auteur",
        ["Common_Description"] = "Description",
        ["Common_Language"] = "Langue",
        ["Common_Status"] = "État",
        ["Common_Folder"] = "Dossier",
        ["Common_Ready"] = "Prêt",
        ["Common_Dash"] = "-",

        // ---- Sélecteur de langue ----
        ["Lang_SelectorTooltip"] = "Changer la langue de l'application",
        ["Lang_Changed"] = "Langue de l'application définie sur {0}.",
        ["Lang_ChangedToEnglish"] = "Langue de l'application définie sur l'anglais.",
        ["Lang_ChangedToFrench"] = "Langue de l'application définie sur le français.",

        // ---- Barre d'outils ----
        ["Toolbar_SearchSermonsTooltip"] = "Rechercher des sermons par titre, code, expression ou numéro de paragraphe",
        ["Toolbar_FontSizeTooltip"] = "Taille du texte de projection",
        ["Toolbar_DecreaseTextTooltip"] = "Réduire la taille du texte",
        ["Toolbar_FitTextTooltip"] = "Ajuster le texte à l'écran",
        ["Toolbar_IncreaseTextTooltip"] = "Augmenter la taille du texte",
        ["Toolbar_Fit"] = "Ajuster",

        // ---- Navigation / bibliothèque ----
        ["Nav_Library"] = "Bibliothèque",
        ["Nav_Sermons"] = "Sermons",
        ["Nav_Bible"] = "Bible",
        ["Nav_Songs"] = "Chants",
        ["Nav_Favorites"] = "Favoris",
        ["Nav_History"] = "Historique",

        // ---- Panneaux ----
        ["Panel_BiblePreview"] = "Aperçu de la Bible",
        ["Panel_SongSections"] = "Sections du chant",
        ["Panel_ReadingSermon"] = "Lecture du sermon",
        ["Panel_LiveProjection"] = "Direct / Projection",
        ["Panel_SearchResults"] = "Résultats de recherche",
        ["Panel_SermonsBreadcrumb"] = "Sermons > {0}",

        // ---- Sermons ----
        ["Sermon_SearchHint"] = "Rechercher des sermons par titre, code, expression ou numéro de paragraphe.",
        ["Sermon_SearchHintShort"] = "Rechercher par titre de sermon, code, expression ou numéro de paragraphe.",
        ["Sermon_Open"] = "Ouvrir le sermon",
        ["Sermon_OpenTooltip"] = "Ouvrir tous les paragraphes de ce sermon pour une lecture suivie",
        ["Sermon_OpenSelectedTooltip"] = "Ouvrir tous les paragraphes du sermon sélectionné pour une lecture suivie",
        ["Sermon_ReadyToSearch"] = "Prêt à rechercher dans les sermons.",
        ["Sermon_ReadyToSearchHeader"] = "Prêt à rechercher dans les sermons",
        ["Sermon_Back"] = "Retour",
        ["Sermon_BackTooltip"] = "Revenir aux résultats de sermons précédents",
        ["Sermon_FindInTooltip"] = "Rechercher dans le sermon sélectionné",
        ["Sermon_PreviousMatch"] = "Occurrence précédente",
        ["Sermon_NextMatch"] = "Occurrence suivante",
        ["Sermon_PreviousPage"] = "Page précédente",
        ["Sermon_NextPage"] = "Page suivante",
        ["Sermon_PreviousParagraph"] = "Paragraphe précédent",
        ["Sermon_NextParagraph"] = "Paragraphe suivant",
        ["Sermon_ParagraphLabel"] = "Paragraphe {0}",
        ["Sermon_NoFrenchContent"] = "Aucun sermon en français n'est encore disponible.",
        ["Sermon_NoFrenchContentDetail"] = "Les sermons en français n'ont pas encore été ajoutés à cette bibliothèque. Les sermons en anglais restent dans l'interface anglaise et ne sont jamais présentés comme du contenu français.",
        ["Sermon_NoContentForLanguage"] = "Aucun sermon n'est encore disponible en {0}.",
        ["Sermon_NoContentForLanguageDetail"] = "Les sermons en {0} n'ont pas encore été ajoutés à cette bibliothèque. Le contenu des autres langues reste dans sa propre interface et n'est jamais présenté ici.",

        // ---- Bible ----
        ["Bible_SearchHint"] = "Rechercher par livre, chapitre, verset ou mot-clé.",
        ["Bible_SearchTooltip"] = "Rechercher une référence biblique ou un mot-clé",
        ["Bible_NotAvailable"] = "La Bible n'est pas disponible. Ouvrez l'Administration si une configuration est nécessaire.",
        ["Bible_ReadyToSearch"] = "Prêt à rechercher dans la Bible.",
        ["Bible_ReadyToSearchHeader"] = "Prêt à rechercher dans la Bible",
        ["Bible_ReferenceExamples"] = "Exemples : Jean 3:16, Romains 8:28, Psaumes 23.",
        ["Bible_PreviousVerse"] = "Verset précédent",
        ["Bible_NextVerse"] = "Verset suivant",
        ["Bible_AddFavorite"] = "Ajouter aux favoris",
        ["Bible_RemoveFavorite"] = "Retirer des favoris",
        ["Bible_Book"] = "Livre",
        ["Bible_Chapter"] = "Chapitre",
        ["Bible_SelectBookHint"] = "Sélectionnez ce livre pour choisir un chapitre.",
        ["Bible_SelectChapterHint"] = "Sélectionnez ce chapitre pour choisir un verset.",
        ["Bible_ChapterMeta"] = "Chapitre | {0}",
        ["Bible_NoTranslationForLanguage"] = "Aucune traduction de la Bible n'est encore disponible pour cette langue.",

        // ---- Chants ----
        ["Song_SearchHint"] = "Rechercher des chants par titre ou paroles.",
        ["Song_SearchTooltip"] = "Rechercher des chants par titre ou paroles",
        ["Song_SearchHintShort"] = "Rechercher par titre ou extrait de paroles.",
        ["Song_ReadyToSearch"] = "Prêt à rechercher dans les chants.",
        ["Song_ReadyToSearchHeader"] = "Prêt à rechercher dans les chants",
        ["Song_PreviousSection"] = "Section précédente",
        ["Song_NextSection"] = "Section suivante",
        ["Song_Source"] = "Source du chant",
        ["Song_NoFrenchContent"] = "Aucun chant en français n'est encore disponible.",
        ["Song_NoFrenchContentDetail"] = "Les chants en français n'ont pas encore été ajoutés à cette bibliothèque. Les chants en anglais restent dans l'interface anglaise et ne sont jamais présentés comme du contenu français.",
        ["Song_NoContentForLanguage"] = "Aucun chant n'est encore disponible en {0}.",
        ["Song_NoContentForLanguageDetail"] = "Les chants en {0} n'ont pas encore été ajoutés à cette bibliothèque. Le contenu des autres langues reste dans sa propre interface et n'est jamais présenté ici.",

        // ---- Favoris ----
        ["Fav_None"] = "Aucun favori pour le moment.",
        ["Fav_NoneDetail"] = "Enregistrez les paragraphes de sermons ou les versets bibliques fréquemment utilisés pour y accéder rapidement.",
        ["Fav_SermonSection"] = "Favoris de sermons",
        ["Fav_BibleSection"] = "Favoris bibliques",
        ["Fav_NoSermonFavorites"] = "Aucun favori de sermon pour le moment.",
        ["Fav_NoBibleFavorites"] = "Aucun favori biblique pour le moment.",
        ["Fav_Remove"] = "Retirer des favoris",
        ["Fav_Add"] = "Ajouter aux favoris",
        ["Fav_SavedAt"] = "Enregistré le {0}",

        // ---- Historique ----
        ["History_Recent"] = "Projections récentes",
        ["History_Clear"] = "Effacer l'historique",
        ["History_None"] = "Aucun historique de projection pour le moment.",

        // ---- Noms dénombrables (singulier / pluriel) ----
        ["Count_BibleResult_One"] = "résultat biblique",
        ["Count_BibleResult_Many"] = "résultats bibliques",
        ["Count_Song_One"] = "chant",
        ["Count_Song_Many"] = "chants",
        ["Count_Sermon_One"] = "sermon",
        ["Count_Sermon_Many"] = "sermons",
        ["Count_Paragraph_One"] = "paragraphe",
        ["Count_Paragraph_Many"] = "paragraphes",
        ["Count_Chapter_One"] = "chapitre",
        ["Count_Chapter_Many"] = "chapitres",
        ["Count_Verse_One"] = "verset",
        ["Count_Verse_Many"] = "versets",
        ["Count_NoResults"] = "Aucun résultat trouvé",

        // ---- Administration ----
        ["Admin_Title"] = "Administration",
        ["Admin_Subtitle"] = "Outils de configuration et de maintenance réservés à l'administrateur. Ces commandes ne sont pas nécessaires pendant un culte normal.",
        ["Admin_Section1"] = "1. Écrans",
        ["Admin_Section1Detail"] = "Choisir et vérifier l'écran de projection de l'église.",
        ["Admin_TestProjection"] = "Tester l'écran de projection",
        ["Admin_TestProjectionTooltip"] = "Afficher une mire de test sur l'écran configuré",
        ["Admin_OpenProjectionPreview"] = "Ouvrir l'aperçu de projection",
        ["Admin_OpenProjectionPreviewTooltip"] = "Ouvrir une fenêtre d'aperçu local redimensionnable",
        ["Admin_RefreshDisplays"] = "Actualiser les écrans",
        ["Admin_RefreshDisplaysTooltip"] = "Détecter à nouveau les moniteurs connectés",
        ["Admin_Section2"] = "2. Importation de la bibliothèque",
        ["Admin_Section2Detail"] = "Analyser et vérifier le contenu local avant son entrée dans la bibliothèque de recherche.",
        ["Admin_OpenLibraryImport"] = "Ouvrir l'importation de bibliothèque",
        ["Admin_OpenLibraryImportTooltip"] = "Importer des PDF locaux de Frère Frank ou des fichiers de chants supplémentaires dans le stockage géré",
        ["Admin_ManageSources"] = "Gérer les sources existantes",
        ["Admin_ManageSourcesTooltip"] = "Vérifier les sources de contenu de sermons configurées",
        ["Admin_AddSermonSource"] = "Ajouter une source de sermons",
        ["Admin_AddSermonSourceTooltip"] = "Configurer un dossier local de PDF existant",
        ["Admin_ImportSelectedSource"] = "Importer la source sélectionnée",
        ["Admin_ImportSelectedSourceTooltip"] = "Analyser et importer la source configurée sélectionnée",
        ["Admin_ImportBible"] = "Importer une Bible",
        ["Admin_ImportBibleTooltip"] = "Importer un fichier CSV de Bible vérifié",
        ["Admin_Section3"] = "3. Maintenance de la recherche",
        ["Admin_Section3Detail"] = "Réparer les métadonnées ou reconstruire l'index de recherche des sermons sans modifier le texte religieux.",
        ["Admin_RepairMetadata"] = "Réparer les métadonnées de la source sélectionnée",
        ["Admin_RepairMetadataTooltip"] = "Relire les titres et les codes depuis les noms de fichiers ; le texte des paragraphes reste inchangé",
        ["Admin_RebuildIndex"] = "Reconstruire l'index de recherche des sermons",
        ["Admin_RebuildIndexTooltip"] = "Reconstruire l'index SQLite des sermons à partir du texte des paragraphes enregistré",
        ["Admin_Section4"] = "4. Base de données / Sauvegarde",
        ["Admin_Section4Detail"] = "Protéger la bibliothèque avant les importations importantes ou la maintenance.",
        ["Admin_BackupDatabase"] = "Sauvegarder la base de données",
        ["Admin_RestoreDatabase"] = "Restaurer la base de données",
        ["Admin_OpenBackupFolder"] = "Ouvrir le dossier de sauvegarde",
        ["Admin_VerifyProductionData"] = "Vérifier les données de production",
        ["Admin_VerifyProductionDataTooltip"] = "Exécuter les contrôles protégés de la Bible, des chants et des sermons",
        ["Admin_Section5"] = "5. À propos / Informations système",
        ["Admin_AdvancedCleanup"] = "Nettoyage avancé (administrateur uniquement)",
        ["Admin_AdvancedCleanupDetail"] = "Ces actions affichent toujours une vérification ou une confirmation avant de modifier les données.",
        ["Admin_CleanupTestData"] = "Nettoyer les données de test",
        ["Admin_CleanupTestDataTooltip"] = "Vérifier et supprimer les enregistrements identifiés comme données de test",
        ["Admin_CleanupBrotherFrank"] = "Nettoyer les lettres circulaires de Frère Frank",
        ["Admin_CleanupBrotherFrankTooltip"] = "Vérifier et supprimer uniquement les lettres circulaires importées",

        // ---- Importer une Bible ----
        ["ImportBible_Title"] = "Importer une Bible",
        ["ImportBible_Subtitle"] = "Sélectionnez un fichier CSV de Bible vérifié contenant les colonnes book, chapter, verse, text.",
        ["ImportBible_SuggestedFile"] = "Dossier suggéré : Documents\\Bible",
        ["ImportBible_TranslationName"] = "Nom de la traduction",
        ["ImportBible_Abbreviation"] = "Abréviation",
        ["ImportBible_Language"] = "Langue",
        ["ImportBible_CsvFile"] = "Fichier CSV",
        ["ImportBible_ChooseFileHint"] = "Choisissez un fichier CSV puis cliquez sur Aperçu.",
        ["ImportBible_Translation"] = "Traduction",
        ["ImportBible_VersesFound"] = "Versets trouvés",
        ["ImportBible_InvalidRows"] = "Lignes non valides",
        ["ImportBible_SampleVerses"] = "10 premiers versets d'exemple",
        ["ImportBible_InvalidRowsList"] = "Lignes non valides",
        ["ImportBible_NoInvalidRows"] = "Aucune ligne non valide trouvée.",
        ["ImportBible_Footer"] = "L'aperçu vérifie uniquement le fichier. Démarrer l'importation écrit les versets prévisualisés dans la base de données.",
        ["ImportBible_StartImport"] = "Démarrer l'importation",
        ["ImportBible_PreviewReady"] = "Aperçu prêt.",
        ["ImportBible_PreviewFailed"] = "L'aperçu a échoué.",
        ["ImportBible_NoValidVerses"] = "Aucun verset valide trouvé.",
        ["ImportBible_FixInvalidRows"] = "Corrigez les lignes non valides avant d'importer.",
        ["ImportBible_ClickPreview"] = "Cliquez sur Aperçu pour examiner le fichier CSV.",
        ["ImportBible_NameRequired"] = "Le nom de la traduction est obligatoire.",
        ["ImportBible_AbbreviationRequired"] = "L'abréviation est obligatoire.",
        ["ImportBible_LanguageRequired"] = "La langue est obligatoire.",
        ["ImportBible_SelectExistingFile"] = "Sélectionnez un fichier CSV de Bible local existant.",
        ["ImportBible_NoCleanPreview"] = "Aucun aperçu de Bible valide n'est prêt à être importé.",
        ["ImportBible_SelectCsvDialog"] = "Sélectionner le fichier CSV de la Bible",
        ["ImportBible_PreviewErrorTitle"] = "Aperçu de l'importation de la Bible",
        ["ImportBible_AlreadyExists"] = "{0} existe déjà. Remplacer les versets existants ?",
        ["ImportBible_ImportedMessage"] = "{0} versets importés pour {1} ({2}).",

        // ---- Aperçu d'importation ----
        ["ImportPreview_Title"] = "Aperçu de l'importation",
        ["ImportPreview_Source"] = "Source",
        ["ImportPreview_Type"] = "Type",
        ["ImportPreview_EstimatedAuthor"] = "Auteur estimé",
        ["ImportPreview_PdfFilesFound"] = "Fichiers PDF trouvés",
        ["ImportPreview_ReadyToImport"] = "Prêt à importer",
        ["ImportPreview_AlreadyImported"] = "Déjà importé",
        ["ImportPreview_InvalidOrMissing"] = "Non valide ou manquant",
        ["ImportPreview_QualityHeading"] = "Aperçu de la qualité des paragraphes de Frère Frank",
        ["ImportPreview_TotalParagraphs"] = "Total des paragraphes extraits",
        ["ImportPreview_AcceptedParagraphs"] = "Paragraphes acceptés",
        ["ImportPreview_RejectedPageNumbers"] = "Numéros de page rejetés",
        ["ImportPreview_RejectedCorrupted"] = "Texte corrompu rejeté",
        ["ImportPreview_RejectedHeaders"] = "En-têtes/pieds de page rejetés",
        ["ImportPreview_RejectedTooShort"] = "Trop courts, rejetés",
        ["ImportPreview_SampleMetadata"] = "Exemple de métadonnées analysées",
        ["ImportPreview_CodeYear"] = "Code / Année",
        ["ImportPreview_TypeStatus"] = "Type / État",
        ["ImportPreview_InvalidFiles"] = "Fichiers non valides ou manquants",
        ["ImportPreview_Footer"] = "Annuler s'arrête ici. Démarrer l'importation n'écrit dans la base de données que les nouveaux PDF locaux.",

        // ---- Importation de bibliothèque ----
        ["LibraryImport_Title"] = "Importation de bibliothèque",
        ["LibraryImport_Subtitle"] = "Importer des fichiers déjà téléchargés sur cet ordinateur. Les fichiers acceptés sont copiés dans le stockage géré par MessageFlow. Aucun accès Internet, aucune complétion par IA et aucune OCR ne sont utilisés.",
        ["LibraryImport_BrotherFrank"] = "Publications de Frère Frank",
        ["LibraryImport_AdditionalSongs"] = "Chants supplémentaires",
        ["LibraryImport_BrowseFiles"] = "Parcourir les fichiers",
        ["LibraryImport_BrowseFilesTooltip"] = "Choisir un ou plusieurs fichiers locaux",
        ["LibraryImport_BrowseFolder"] = "Parcourir le dossier",
        ["LibraryImport_BrowseFolderTooltip"] = "Choisir un dossier local à analyser",
        ["LibraryImport_ColumnImport"] = "Importer",
        ["LibraryImport_ColumnFile"] = "Fichier",
        ["LibraryImport_ColumnTitle"] = "Titre (modifiable)",
        ["LibraryImport_ColumnItems"] = "Éléments",
        ["LibraryImport_ColumnStatus"] = "État d'analyse / importation",
        ["LibraryImport_Hint"] = "Choisissez des fichiers ou un dossier, puis vérifiez les résultats de l'analyse.",
        ["LibraryImport_ImportSelected"] = "Importer la sélection",
        ["LibraryImport_ImportSelectedTooltip"] = "Copier et importer de façon transactionnelle les fichiers cochés",

        // ---- Gérer les sources ----
        ["ManageSources_Title"] = "Gérer les sources",
        ["ManageSources_Subtitle"] = "Vérifier les dossiers locaux et lancer les importations de sources depuis cet écran.",
        ["ManageSources_ShowTestSources"] = "Afficher les sources de test",
        ["ManageSources_Sources"] = "Sources",
        ["ManageSources_Documents"] = "Documents",
        ["ManageSources_Paragraphs"] = "Paragraphes",
        ["ManageSources_RepairMetadata"] = "Réparer les métadonnées",
        ["ManageSources_AdvancedDetails"] = "Détails avancés",
        ["ManageSources_LocalPdfs"] = "PDF locaux",
        ["ManageSources_TestSource"] = "Source de test",
        ["ManageSources_Suspicious"] = "Suspect",
        ["ManageSources_AddSource"] = "Ajouter une source",

        // ---- Ajouter une source ----
        ["AddSource_Title"] = "Ajouter une nouvelle source",
        ["AddSource_Subtitle"] = "Enregistrer un dossier de contenu local pour de futures importations.",
        ["AddSource_DisplayName"] = "Nom affiché",
        ["AddSource_SourceType"] = "Type de source",
        ["AddSource_LocalFolderPath"] = "Chemin du dossier local",
        ["AddSource_Save"] = "Enregistrer la source",

        // ---- Vérification des données ----
        ["Verify_Title"] = "Contrôle des données de production",
        ["Verify_Subtitle"] = "Un rapport simple de préparation pour l'usage média de l'église.",

        // ---- Nettoyage des données de test ----
        ["Cleanup_Title"] = "Nettoyer les données de test",
        ["Cleanup_Documents"] = "Documents : ",
        ["Cleanup_Paragraphs"] = "  Paragraphes : ",
        ["Cleanup_Favorites"] = "  Favoris : ",
        ["Cleanup_History"] = "  Historique : ",
        ["Cleanup_TypePhrase"] = "Saisissez cette phrase de confirmation pour continuer :",
        ["Cleanup_Phrase"] = "I understand this removes test source data only.",
        ["Cleanup_BackupNotice"] = "Une sauvegarde de la base de données sera créée avant toute suppression.",

        // ---- Projection ----
        ["Projection_Title"] = "Projection MessageFlow",

        // ---- Messages d'état ----
        ["Status_Ready"] = "Prêt",
        ["Status_ProjectionDisplaySet"] = "Écran de projection défini sur {0}.",
        ["Status_Selected"] = "{0} sélectionné.",
        ["Status_SelectedParagraph"] = "Paragraphe {0} sélectionné.",
        ["Status_Projecting"] = "Projection de {0}.",
        ["Status_ProjectingParagraph"] = "Projection du paragraphe {0}.",
        ["Status_ProjectingSongSection"] = "Projection de {0} - {1}.",
        ["Status_MetadataRefreshed"] = "Métadonnées des publications de Frère Frank actualisées.",
        ["Status_MetadataRefreshFailed"] = "Les métadonnées des publications de Frère Frank n'ont pas pu être actualisées. La réparation par l'Administration reste disponible.",
        ["Status_LibrarySearchable"] = "Le contenu importé est désormais accessible à la recherche.",
        ["Status_HistoryKept"] = "L'historique a été conservé.",
        ["Status_HistoryCleared"] = "Historique effacé.",
        ["Status_HistoryClearFailed"] = "L'historique n'a pas pu être effacé : {0}",
        ["Status_VerifyingProductionData"] = "Vérification des données de production...",
        ["Status_ProductionVerificationFailed"] = "La vérification de production a échoué : {0}",
        ["Status_IndexRebuildCanceled"] = "Reconstruction de l'index des sermons annulée.",
        ["Status_RebuildingIndex"] = "Reconstruction de l'index de recherche des sermons...",
        ["Status_IndexRebuilt"] = "Index de recherche des sermons reconstruit.",
        ["Status_IndexRebuildFailed"] = "La reconstruction de l'index des sermons a échoué : {0}",
        ["Status_CheckingTestData"] = "Recherche de données de test...",
        ["Status_NoTestData"] = "Aucune donnée de test n'a été trouvée.",
        ["Status_TestCleanupCanceled"] = "Nettoyage des données de test annulé.",
        ["Status_TestCleanupCompleted"] = "Nettoyage des données de test terminé.",
        ["Status_TestCleanupFailed"] = "Le nettoyage des données de test a échoué : {0}",
        ["Status_CheckingBrotherFrank"] = "Vérification des lettres circulaires importées de Frère Frank...",
        ["Status_BrotherFrankPreviewFailed"] = "L'aperçu du nettoyage de Frère Frank a échoué : {0}",
        ["Status_NoBrotherFrankImports"] = "Aucune lettre circulaire importée de Frère Frank n'a été trouvée.",
        ["Status_BrotherFrankCanceled"] = "Nettoyage de Frère Frank annulé.",
        ["Status_RemovingBrotherFrank"] = "Suppression des lettres circulaires importées de Frère Frank...",
        ["Status_BrotherFrankFailed"] = "Le nettoyage de Frère Frank a échoué : {0}",
        ["Status_BackingUp"] = "Sauvegarde de la base de données...",
        ["Status_BackupCompleted"] = "Sauvegarde réussie :{0}{1}",
        ["Status_BackupFailed"] = "La sauvegarde a échoué : {0}",
        ["Status_Restoring"] = "Restauration de la base de données...",
        ["Status_RestoreCompleted"] = "Restauration réussie.",
        ["Status_RestoreFailed"] = "La restauration a échoué : {0}",
        ["Status_NoBackupYet"] = "Aucune sauvegarde n'a encore été créée.",
        ["Status_BackupFolderMissing"] = "Le dossier de sauvegarde n'a pas pu être trouvé.",
        ["Status_OpenBackupFolderFailed"] = "L'ouverture du dossier de sauvegarde a échoué : {0}",
        ["Status_SavingSource"] = "Enregistrement de la source de contenu...",
        ["Status_SourceExists"] = "Une source nommée {0} existe déjà.",
        ["Status_SourceAdded"] = "Source ajoutée : {0}.",
        ["Status_SourceSaveFailed"] = "L'enregistrement de la source a échoué : {0}",
        ["Status_BibleImportCanceled"] = "Importation de la Bible annulée. Aucune modification n'a été apportée à la base de données.",
        ["Status_NoBibleVerses"] = "Aucun verset biblique n'est prêt à être importé.",
        ["Status_PreparingBibleImport"] = "Préparation de l'importation de la Bible {0}...",
        ["Status_BibleImportKeptExisting"] = "Importation de la Bible annulée. Les versets existants ont été conservés.",
        ["Status_BibleImported"] = "{0} importée : {1} versets.",
        ["Status_BibleImportFailed"] = "L'importation de la Bible a échoué : {0}",
        ["Status_SelectSourceFirst"] = "Sélectionnez une source avant d'importer.",
        ["Status_ImportComingSoon"] = "L'importation pour ce type de source arrive bientôt.",
        ["Status_SourceFolderMissing"] = "Le dossier source n'existe pas.",
        ["Status_ScanningSource"] = "Analyse de {0} pour l'aperçu d'importation...",
        ["Status_ImportPreviewFailed"] = "L'aperçu de l'importation a échoué : {0}",
        ["Status_ImportCanceled"] = "Importation annulée. Aucune modification n'a été apportée à la base de données.",
        ["Status_NoNewPdfs"] = "Aucun nouveau fichier PDF n'est prêt à être importé.",
        ["Status_StartingImport"] = "Démarrage de l'importation pour {0}...",
        ["Status_SourceImportFailed"] = "L'importation de la source a échoué : {0}",
        ["Status_SelectSourceRepair"] = "Sélectionnez une source avant de réparer les métadonnées.",
        ["Status_BranhamProtected"] = "Les métadonnées de Frère Branham sont protégées et n'ont pas été modifiées.",
        ["Status_RepairLimited"] = "Cette réparation est actuellement limitée aux sources de publications d'Ewald Frank.",
        ["Status_CheckingRepairPreview"] = "Vérification de l'aperçu de réparation pour {0}...",
        ["Status_RepairPreviewFailed"] = "L'aperçu de la réparation des métadonnées a échoué : {0}",
        ["Status_NoDocumentsForSource"] = "Aucun document n'a été trouvé pour {0}.",
        ["Status_RepairCanceled"] = "Réparation des métadonnées annulée.",
        ["Status_RepairingMetadata"] = "Réparation des métadonnées pour {0}...",
        ["Status_RepairFailed"] = "La réparation des métadonnées a échoué : {0}",
        ["Status_UseSearchInsideSermon"] = "Utilisez la recherche dans ce sermon, ou revenez aux résultats de recherche.",
        ["Status_SearchingBible"] = "Recherche dans la Bible...",
        ["Status_BibleSearchFailed"] = "La recherche biblique a échoué : {0}",
        ["Status_ChaptersFound"] = "{0} trouvés pour {1}.",
        ["Status_NoMatchingVerse"] = "Aucun verset biblique correspondant n'a été trouvé.",
        ["Status_BibleQuickProjectFailed"] = "La projection rapide du verset a échoué : {0}",
        ["Status_SongSearchFailed"] = "La recherche de chants a échoué : {0}",
        ["Status_SongSectionsFailed"] = "Impossible de charger les sections du chant : {0}",
        ["Status_Searching"] = "Recherche...",
        ["Status_NoMatchingParagraph"] = "Aucun paragraphe correspondant n'a été trouvé.",
        ["Status_SearchFailed"] = "La recherche a échoué : {0}",
        ["Status_SelectSermonThenOpen"] = "Sélectionnez un sermon, puis choisissez Ouvrir le sermon.",
        ["Status_CouldNotOpenSermon"] = "Impossible d'ouvrir le sermon : {0}",
        ["Status_CouldNotMoveBible"] = "Impossible de déplacer la sélection biblique : {0}",
        ["Status_SelectVerseBeforeCopy"] = "Veuillez sélectionner un verset biblique avant de copier.",
        ["Status_BibleVerseCopied"] = "Verset biblique copié.",
        ["Status_SelectSectionBeforeCopy"] = "Veuillez sélectionner une section de chant avant de copier.",
        ["Status_SongSectionCopied"] = "Section de chant copiée.",
        ["Status_ParagraphCopied"] = "Paragraphe copié.",
        ["Status_SelectParagraphBeforeProject"] = "Veuillez sélectionner un paragraphe avant de projeter.",
        ["Status_SelectSavedParagraphBeforeProject"] = "Veuillez sélectionner un paragraphe enregistré avant de projeter.",
        ["Status_SelectBibleFavoriteBeforeProject"] = "Veuillez sélectionner un favori biblique avant de projeter.",
        ["Status_SelectBibleFavoriteBeforeCopy"] = "Veuillez sélectionner un favori biblique avant de copier.",
        ["Status_Copied"] = "{0} copié.",
        ["Status_SelectFavoriteToRemove"] = "Veuillez sélectionner un favori à retirer.",
        ["Status_FavoriteRemoved"] = "Favori retiré.",
        ["Status_FavoriteRemoveFailed"] = "Le favori n'a pas pu être retiré : {0}",
        ["Status_SelectBibleFavoriteToRemove"] = "Veuillez sélectionner un favori biblique à retirer.",
        ["Status_RemovedFromFavorites"] = "{0} retiré des favoris.",
        ["Status_BibleFavoriteRemoveFailed"] = "Le favori biblique n'a pas pu être retiré : {0}",
        ["Status_SelectVerseBeforeProject"] = "Veuillez sélectionner un verset biblique avant de projeter.",
        ["Status_SelectSectionBeforeProject"] = "Veuillez sélectionner une section de chant avant de projeter.",
        ["Status_SongFavoritesNotEnabled"] = "Les favoris de chants ne sont pas encore activés.",
        ["Status_ParagraphAddedToFavorites"] = "Paragraphe ajouté aux favoris.",
        ["Status_ParagraphRemovedFromFavorites"] = "Paragraphe retiré des favoris.",
        ["Status_FavoriteUpdateFailed"] = "La mise à jour du favori a échoué : {0}",
        ["Status_AddedToFavorites"] = "{0} ajouté aux favoris.",
        ["Status_BibleFavoriteUpdateFailed"] = "La mise à jour du favori biblique a échoué : {0}",
        ["Status_SavedParagraphMissing"] = "Le paragraphe enregistré n'a pas pu être trouvé.",
        ["Status_CouldNotSelectSavedParagraph"] = "Impossible de sélectionner le paragraphe enregistré : {0}",
        ["Status_NoContentSources"] = "Aucune source de contenu n'est encore configurée.",
        ["Status_ProjectionTextDecreased"] = "Texte de projection réduit de 2 DIP.",
        ["Status_ProjectionTextRestored"] = "Texte de projection rétabli au plus grand ajustement sûr.",
        ["Status_SavedToHistory"] = "Enregistré dans l'historique de projection.",
        ["Status_HistoryUpdateFailed"] = "La mise à jour de l'historique de projection a échoué : {0}",

        // ---- Informations sur la traduction ----
        ["Info_CurrentTranslation"] = "Bible actuelle : {0} ({1})",
        ["Info_NoTranslation"] = "Aucune traduction de la Bible n'est chargée.",
        ["Info_NoTranslationImported"] = "Aucune traduction de la Bible n'a encore été importée.",
        ["Info_VersionNone"] = "Version : aucune",
        ["Info_Version"] = "Version : {0}",
        ["Info_NoVersesImported"] = "Aucun verset biblique n'a été importé.",
        ["Info_VerseCount"] = "{0} versets disponibles.",

        ["Filter_AllAuthors"] = "Tous les auteurs",
        ["Filter_AllSources"] = "Toutes les sources",
        ["Filter_AllYears"] = "Toutes les années",
        ["Font_Small"] = "Petit",
        ["Font_Medium"] = "Moyen",
        ["Font_Large"] = "Grand",
        ["Font_ExtraLarge"] = "Très grand",
        ["Panel_CircularLetterResults"] = "Résultats des lettres circulaires",
        ["Panel_SermonResults"] = "Résultats des sermons",
        ["Count_BibleBook_One"] = "livre biblique",
        ["Count_BibleBook_Many"] = "livres bibliques",
        ["Count_Document_One"] = "document",
        ["Count_Document_Many"] = "documents",
        ["Status_LoadingSongs"] = "Chargement des chants...",
        ["Status_SearchingSongs"] = "Recherche de chants...",
        ["Status_NoSongsFound"] = "Aucun chant trouvé.",
        ["Status_NoBibleMatches"] = "Aucune correspondance biblique trouvée.",
        ["Status_VerseNotFound"] = "{0} n'a pas été trouvé.",
        ["Status_VersesFoundIn"] = "{0} trouvés dans {1}.",
        ["Status_SelectedInChapterContext"] = "{0} sélectionné dans le contexte du chapitre.",
        ["Status_BooksFound"] = "{0} trouvés.",
        ["Status_StartupFailed"] = "L'initialisation a échoué. Voir logs\\app-startup.log.",
        ["Status_FindInSermon"] = "Rechercher dans le sermon sélectionné.",
        ["Status_ProjectionOpen"] = "Projection : ouverte sur {0}",
        ["Status_ProjectionClosed"] = "Projection : fermée",
        ["Status_NoExactPhrase"] = "Aucune expression exacte trouvée",
        ["Status_ExactPhrase"] = "Expression exacte",
        ["Status_AllWords"] = "Tous les mots",
        ["Status_Match"] = "Correspondance",
        ["Status_BrowseFound"] = "{0} trouvés en {1} ms.",
        ["Status_SearchFound"] = "{0} trouvée dans {1} ({2}) en {3} ms.",
        ["Status_SearchNoMatch"] = "{0} en {1} ms.",
        ["Fav_KindFavorite"] = "Favori",
        ["Fav_KindHistory"] = "Historique",
        ["Meta_Paragraph"] = "Paragraphe {0}",
        ["Sermon_FindInSelected"] = "Rechercher dans le sermon sélectionné.",
        ["Display_Auto"] = "Auto - préférer l'écran de projection secondaire",
        ["Display_Primary"] = "Principal / Opérateur",
        ["Display_Secondary"] = "Secondaire / Projection",
        ["Display_Selector"] = "Écran {0} - {1} - {2}x{3}",
        ["Display_StatusPrimary"] = "Écran {0} Principal / Opérateur",
        ["Display_StatusSecondary"] = "Écran {0} Secondaire / Projection",
        ["Confirm_ClearHistory"] = "Effacer tout l'historique de projection ? Cela ne supprimera pas les sermons, les versets bibliques, les favoris ni les sources.",
        ["Confirm_ClearHistoryTitle"] = "Effacer l'historique",
        ["Confirm_RebuildIndex"] = "Reconstruire l'index de recherche des sermons ? Cela ne modifie pas le texte des sermons, les importations PDF, les versets bibliques, les chants, les favoris ni l'historique de projection.",
        ["Confirm_RebuildIndexTitle"] = "Reconstruire l'index de recherche des sermons",
        ["Confirm_RestoreDatabase"] = "La restauration remplacera la base de données actuelle. Continuer ?",
        ["Confirm_RestoreDatabaseTitle"] = "Restaurer la base de données MessageFlow",
        ["Confirm_ImportBibleReplace"] = "{0} existe déjà. Remplacer les versets existants ?",
        ["Msg_StartupFailed"] = "MessageFlow s'est ouvert, mais l'initialisation a échoué.{0}{0}{1}{0}{0}Les détails ont été écrits dans logs\\app-startup.log.",
        ["Msg_StartupFailedTitle"] = "Erreur de démarrage MessageFlow"
    };
}
