<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\MessageFlow.Core\MessageFlow.Core.csproj" />
    <ProjectReference Include="..\..\src\MessageFlow.Data\MessageFlow.Data.csproj" />
    <ProjectReference Include="..\..\src\MessageFlow.Importer\MessageFlow.Importer.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
