namespace MessageFlow.Core.Bible;

public static class BibleBookSeed
{
    public static IReadOnlyList<BibleBook> All { get; } =
    [
        new() { Id = 1, Name = "Genesis", ShortName = "Gen", BookOrder = 1 },
        new() { Id = 2, Name = "Exodus", ShortName = "Exo", BookOrder = 2 },
        new() { Id = 3, Name = "Leviticus", ShortName = "Lev", BookOrder = 3 },
        new() { Id = 4, Name = "Numbers", ShortName = "Num", BookOrder = 4 },
        new() { Id = 5, Name = "Deuteronomy", ShortName = "Deut", BookOrder = 5 },
        new() { Id = 6, Name = "Joshua", ShortName = "Josh", BookOrder = 6 },
        new() { Id = 7, Name = "Judges", ShortName = "Judg", BookOrder = 7 },
        new() { Id = 8, Name = "Ruth", ShortName = "Ruth", BookOrder = 8 },
        new() { Id = 9, Name = "1 Samuel", ShortName = "1 Sam", BookOrder = 9 },
        new() { Id = 10, Name = "2 Samuel", ShortName = "2 Sam", BookOrder = 10 },
        new() { Id = 11, Name = "1 Kings", ShortName = "1 Kgs", BookOrder = 11 },
        new() { Id = 12, Name = "2 Kings", ShortName = "2 Kgs", BookOrder = 12 },
        new() { Id = 13, Name = "1 Chronicles", ShortName = "1 Chr", BookOrder = 13 },
        new() { Id = 14, Name = "2 Chronicles", ShortName = "2 Chr", BookOrder = 14 },
        new() { Id = 15, Name = "Ezra", ShortName = "Ezra", BookOrder = 15 },
        new() { Id = 16, Name = "Nehemiah", ShortName = "Neh", BookOrder = 16 },
        new() { Id = 17, Name = "Esther", ShortName = "Esth", BookOrder = 17 },
        new() { Id = 18, Name = "Job", ShortName = "Job", BookOrder = 18 },
        new() { Id = 19, Name = "Psalms", ShortName = "Ps", BookOrder = 19 },
        new() { Id = 20, Name = "Proverbs", ShortName = "Prov", BookOrder = 20 },
        new() { Id = 21, Name = "Ecclesiastes", ShortName = "Eccl", BookOrder = 21 },
        new() { Id = 22, Name = "Song of Solomon", ShortName = "Song", BookOrder = 22 },
        new() { Id = 23, Name = "Isaiah", ShortName = "Isa", BookOrder = 23 },
        new() { Id = 24, Name = "Jeremiah", ShortName = "Jer", BookOrder = 24 },
        new() { Id = 25, Name = "Lamentations", ShortName = "Lam", BookOrder = 25 },
        new() { Id = 26, Name = "Ezekiel", ShortName = "Ezek", BookOrder = 26 },
        new() { Id = 27, Name = "Daniel", ShortName = "Dan", BookOrder = 27 },
        new() { Id = 28, Name = "Hosea", ShortName = "Hos", BookOrder = 28 },
        new() { Id = 29, Name = "Joel", ShortName = "Joel", BookOrder = 29 },
        new() { Id = 30, Name = "Amos", ShortName = "Amos", BookOrder = 30 },
        new() { Id = 31, Name = "Obadiah", ShortName = "Obad", BookOrder = 31 },
        new() { Id = 32, Name = "Jonah", ShortName = "Jonah", BookOrder = 32 },
        new() { Id = 33, Name = "Micah", ShortName = "Mic", BookOrder = 33 },
        new() { Id = 34, Name = "Nahum", ShortName = "Nah", BookOrder = 34 },
        new() { Id = 35, Name = "Habakkuk", ShortName = "Hab", BookOrder = 35 },
        new() { Id = 36, Name = "Zephaniah", ShortName = "Zeph", BookOrder = 36 },
        new() { Id = 37, Name = "Haggai", ShortName = "Hag", BookOrder = 37 },
        new() { Id = 38, Name = "Zechariah", ShortName = "Zech", BookOrder = 38 },
        new() { Id = 39, Name = "Malachi", ShortName = "Mal", BookOrder = 39 },
        new() { Id = 40, Name = "Matthew", ShortName = "Matt", BookOrder = 40 },
        new() { Id = 41, Name = "Mark", ShortName = "Mk", BookOrder = 41 },
        new() { Id = 42, Name = "Luke", ShortName = "Lk", BookOrder = 42 },
        new() { Id = 43, Name = "John", ShortName = "Jn", BookOrder = 43 },
        new() { Id = 44, Name = "Acts", ShortName = "Acts", BookOrder = 44 },
        new() { Id = 45, Name = "Romans", ShortName = "Rom", BookOrder = 45 },
        new() { Id = 46, Name = "1 Corinthians", ShortName = "1 Cor", BookOrder = 46 },
        new() { Id = 47, Name = "2 Corinthians", ShortName = "2 Cor", BookOrder = 47 },
        new() { Id = 48, Name = "Galatians", ShortName = "Gal", BookOrder = 48 },
        new() { Id = 49, Name = "Ephesians", ShortName = "Eph", BookOrder = 49 },
        new() { Id = 50, Name = "Philippians", ShortName = "Phil", BookOrder = 50 },
        new() { Id = 51, Name = "Colossians", ShortName = "Col", BookOrder = 51 },
        new() { Id = 52, Name = "1 Thessalonians", ShortName = "1 Thess", BookOrder = 52 },
        new() { Id = 53, Name = "2 Thessalonians", ShortName = "2 Thess", BookOrder = 53 },
        new() { Id = 54, Name = "1 Timothy", ShortName = "1 Tim", BookOrder = 54 },
        new() { Id = 55, Name = "2 Timothy", ShortName = "2 Tim", BookOrder = 55 },
        new() { Id = 56, Name = "Titus", ShortName = "Titus", BookOrder = 56 },
        new() { Id = 57, Name = "Philemon", ShortName = "Phlm", BookOrder = 57 },
        new() { Id = 58, Name = "Hebrews", ShortName = "Heb", BookOrder = 58 },
        new() { Id = 59, Name = "James", ShortName = "Jas", BookOrder = 59 },
        new() { Id = 60, Name = "1 Peter", ShortName = "1 Pet", BookOrder = 60 },
        new() { Id = 61, Name = "2 Peter", ShortName = "2 Pet", BookOrder = 61 },
        new() { Id = 62, Name = "1 John", ShortName = "1 Jn", BookOrder = 62 },
        new() { Id = 63, Name = "2 John", ShortName = "2 Jn", BookOrder = 63 },
        new() { Id = 64, Name = "3 John", ShortName = "3 Jn", BookOrder = 64 },
        new() { Id = 65, Name = "Jude", ShortName = "Jude", BookOrder = 65 },
        new() { Id = 66, Name = "Revelation", ShortName = "Rev", BookOrder = 66 }
    ];
}
