// <auto-generated />
using System;
using MessageFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessageFlow.Data.Migrations
{
    [DbContext(typeof(MessageFlowDbContext))]
    partial class MessageFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MessageFlow.Core.Sermons.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Primary sermon author for the local MessageFlow sermon library.",
                            DisplayName = "Brother Branham",
                            FullName = "William Marrion Branham"
                        });
                });

            modelBuilder.Entity("MessageFlow.Core.Sermons.FavoriteParagraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SermonParagraphId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SermonParagraphId")
                        .IsUnique();

                    b.ToTable("FavoriteParagraphs", (string)null);
                });

            modelBuilder.Entity("MessageFlow.Core.ContentSources.ContentSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalFolderPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ContentSources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Local Brother William Marrion Branham sermon PDF library.",
                            DisplayName = "Brother Branham",
                            LocalFolderPath = "D:\\Br William Marrion Branham\\PDF",
                            Name = "brother_branham",
                            SourceType = "SermonPdfCollection"
                        });
                });

            modelBuilder.Entity("MessageFlow.Core.Sermons.ImportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilePath");

                    b.HasIndex("Status");

                    b.ToTable("ImportLogs", (string)null);
                });

            modelBuilder.Entity("MessageFlow.Core.Sermons.ProjectionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProjectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchQuery")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SermonParagraphId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectedAt");

                    b.HasIndex("SermonParagraphId");

                    b.ToTable("ProjectionHistories", (string)null);
                });

            modelBuilder.Entity("MessageFlow.Core.Sermons.Sermon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContentSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("en");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SermonCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ContentSourceId");

                    b.HasIndex("SermonCode");

                    b.HasIndex("SourceFilePath")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.HasIndex("Year");

                    b.HasIndex("Year", "Title");

                    b.ToTable("Sermons", (string)null);
                });

            modelBuilder.Entity("MessageFlow.Core.Sermons.SermonParagraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParagraphNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SermonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PageNumber");

                    b.HasIndex("ParagraphNumber");

                    b.HasIndex("SermonId", "ParagraphNumber")
                        .IsUnique();

                    b.ToTable("SermonParagraphs", (string)null);
                });

            modelBuilder.Entity("MessageFlow.Core.Sermons.FavoriteParagraph", b =>
                {
                    b.HasOne("MessageFlow.Core.Sermons.SermonParagraph", "SermonParagraph")
                        .WithMany("Favorites")
                        .HasForeignKey("SermonParagraphId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SermonParagraph");
                });

            modelBuilder.Entity("MessageFlow.Core.Sermons.ProjectionHistory", b =>
                {
                    b.HasOne("MessageFlow.Core.Sermons.SermonParagraph", "SermonParagraph")
                        .WithMany("ProjectionHistories")
                        .HasForeignKey("SermonParagraphId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SermonParagraph");
                });

            modelBuilder.Entity("MessageFlow.Core.Sermons.Sermon", b =>
                {
                    b.HasOne("MessageFlow.Core.Sermons.Author", "Author")
                        .WithMany("Sermons")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.HasOne("MessageFlow.Core.ContentSources.ContentSource", "ContentSource")
                        .WithMany("Sermons")
                        .HasForeignKey("ContentSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContentSource");
                });

            modelBuilder.Entity("MessageFlow.Core.Sermons.SermonParagraph", b =>
                {
                    b.HasOne("MessageFlow.Core.Sermons.Sermon", "Sermon")
                        .WithMany("Paragraphs")
                        .HasForeignKey("SermonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sermon");
                });

            modelBuilder.Entity("MessageFlow.Core.Sermons.Author", b =>
                {
                    b.Navigation("Sermons");
                });

            modelBuilder.Entity("MessageFlow.Core.Sermons.Sermon", b =>
                {
                    b.Navigation("Paragraphs");
                });

            modelBuilder.Entity("MessageFlow.Core.ContentSources.ContentSource", b =>
                {
                    b.Navigation("Sermons");
                });

            modelBuilder.Entity("MessageFlow.Core.Sermons.SermonParagraph", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("ProjectionHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
